app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('survey');
    } else {
        return redirect('login');
    }
});

Route::auth();

Route::resource('survey', 'EntryController');
Route::get('export', 'EntryController@export');

Route::get('interview/{id}', 'EntryController@getInterview')->name('interview.get');
Route::put('interview/{id}', 'EntryController@saveInterview')->name('interview.save');

Route::get('consent/{id}', 'EntryController@getConsent')->name('consent.get');
Route::put('consent/{id}', 'EntryController@saveConsent')->name('consent.save');

resources/views/euci.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">New Chart Abstraction Form</div>
                    <div class="panel-body">
                        <form id="euci" action="{{ route('survey.store') }}" method="post" data-confirm="1">
                            {!! csrf_field() !!}
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label>First and third letters of first name:</label>
                                    @if ($errors->has('client_first1'))
                                        <label id="client_first1-error" class="error" for="client_first1">This field is required.</label>
                                    @endif
                                    <input type="text" class="form-control" minlength="1" maxlength="2" required name="client_first1" data-name="client_first">
                                </div>
                                <div class="form-group col-md-6">
                                    <label>First and third letters of last name:</label>
                                    @if ($errors->has('client_last1'))
                                        <label id="client_last1-error" class="error" for="client_last1">This field is required.</label>
                                    @endif
                                    <input type="text" class="form-control" minlength="1" maxlength="2" required name="client_last1" data-name="client_last">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label>Date of birth: <small>Enter January 1 if month and date are unknown</small></label>
                                    @if ($errors->has('client_dob1'))
                                        <label id="client_dob1-error" class="error" for="client_dob1">This field is required.</label>
                                    @endif
                                    <input type="date" class="form-control" required name="client_dob1" data-name="client_dob">
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Current Gender:</label>
                                    @if ($errors->has('client_gender1'))
                                        <label id="client_gender1-error" class="error" for="client_gender1">This field is required.</label>
                                    @endif
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="radio" style="margin:0;">
                                                <label>
                                                    <input type="radio" name="client_gender1" data-name="client_gender" value="1" required>
                                                    Male
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="radio" style="margin:0;">
                                                <label>
                                                    <input type="radio" name="client_gender1" data-name="client_gender" value="2">
                                                    Female
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="radio" style="margin:0;">
                                                <label>
                                                    <input type="radio" name="client_gender1" data-name="client_gender" value="3">
                                                    Transgender
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="radio" style="margin:0;">
                                                <label>
                                                    <input type="radio" name="client_gender1" data-name="client_gender" value="9">
                                                    Unknown
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <nav class="form-nav">
                                <ul class="pager">
                                    <li class="pull-left"><a href="{{ route('survey.index') }}">Cancel</a></li>
                                    <li class="next pull-right"><input type="submit" class="btn btn-primary" value="Next &rarr;"></li>
                                </ul>
                            </nav>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="modal-euci" class="modal fade" tabindex="-1" role="dialog" data-target="euci">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Please confirm these data are correct before proceeding.</p>

                    <div class="well">
                        <div class="row">
                            <div class="col-sm-6">
                                First and third letters of first name: <strong id="ph-first"></strong>
                            </div>
                            <div class="col-sm-6">
                                First and third letters of last name: <strong id="ph-last"></strong>
                            </div>
                            <div class="col-sm-6">
                                Date of birth: <strong id="ph-dob"></strong>
                            </div>
                            <div class="col-sm-6">
                                Current Gender: <strong id="ph-gender"></strong>
                            </div>
                        </div>
                    </div>

                    <p>
                        Click <strong class="text-primary">OK</strong> to initiate Form with these data
                        or <strong class="text-danger">Cancel</strong> to edit.
                        You will not be able to change this information after clicking <strong class="text-primary">OK</strong>.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary modal-ok">OK</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="clearfix" style="margin-bottom:10px;">
                    <h2 class="pull-left">Surveys & Interviews</h2>
                    <h1 class="pull-right"><a class="btn btn-primary" href="{{ route('survey.create') }}">Create New</a></h1>
                </div>

                <div class="table-responsive">
                    <table id="table-entries" class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Last Updated</th>
                            <th>eUCI</th>
                            <th class="text-center">Survey</th>
                            <th class="text-center">Interview</th>
                        </tr>
                        </thead>
                        @if($entries->count())
                            <tbody>
                            @foreach($entries as $e)
                                <?php
                                $surveyStatus = $e->getStatus('survey');
                                $interviewStatus = $e->getStatus('interview');
                                ?>
                                <tr>
                                    <td>{{ $e->id }}</td>
                                    <td>{{ $e->updated_at }}</td>
                                    <td>{{ $e->euci }}</td>
                                    <td class="text-center">
                                        @if ($surveyStatus == \App\Models\Entry::STATUS_COMPLETE)
                                            <strong>Completed</strong>
                                        @else
                                            <a href="{{ route('survey.edit', $e->id) }}" class="btn btn-sm btn-default">
                                                @if ($surveyStatus == \App\Models\Entry::STATUS_PENDING)
                                                    Continue
                                                @else
                                                    Start
                                                @endif
                                            </a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if ($interviewStatus == \App\Models\Entry::STATUS_COMPLETE)
                                            <strong>Completed</strong>
                                        @else
                                            <a href="{{ route('interview.get', $e->id) }}" class="btn btn-sm btn-default">
                                                @if ($interviewStatus == \App\Models\Entry::STATUS_PENDING)
                                                    Continue
                                                @else
                                                    Start
                                                @endif
                                            </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        @endif
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Last Updated</th>
                            <th>eUCI</th>
                            <th class="text-center">Survey</th>
                            <th class="text-center">Interview</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/jquery.dataTables.min.css') }}">
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script>
        jQuery(document).ready(function ($) {
            $('#table-entries').DataTable({
                'order': [[1, 'desc']]
            });

            $('input').first().css("border","1px solid #ccc");

        });
    </script>
@endsection

resources/views/result.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="alert alert-{{ $data['success'] ? 'success' : 'danger' }}">{!! $data['message'] !!}</div>

        <div class="text-center">
            <a href="{{ route('survey.index') }}" class="btn btn-default">OK</a>
            @if ($data['interview_button'])
                <a href="{{ route('interview.get', $data['id']) }}" class="btn btn-primary" style="margin-left:20px;">Continue to Interview</a>
            @endif
        </div>
    </div>
@endsection

resources/views/survey.blade.php
@extends('layouts.app')

@section('content')
    <nav>
        <ul id="nav-main" class="nav nav-tabs nav-justified" role="tablist">
            <li role="presentation" class="active">
                <a href="#tab-pane1" aria-controls="tab-pane1" role="tab" data-toggle="tab">Introduction</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane2" aria-controls="tab-pane2" role="tab" data-toggle="tab">Demographics</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane3" aria-controls="tab-pane3" role="tab" data-toggle="tab">Access to Care and Health Care Coverage</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane4" aria-controls="tab-pane4" role="tab" data-toggle="tab">Stigma</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane5" aria-controls="tab-pane5" role="tab" data-toggle="tab">Medical Mistrust</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane6" aria-controls="tab-pane6" role="tab" data-toggle="tab">Trauma History and Current Exposure</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane7" aria-controls="tab-pane7" role="tab" data-toggle="tab">Coping Self-Efficacy</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane8" aria-controls="tab-pane8" role="tab" data-toggle="tab">Case Adherence Scale</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane9" aria-controls="tab-pane9" role="tab" data-toggle="tab">Substance Use</a>
            </li>
            <li role="presentation">
                <a href="#tab-pane10" aria-controls="tab-pane10" role="tab" data-toggle="tab">Closing</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <form id="survey" action="{{ route('survey.update', $id) }}" method="post" data-confirm="1">
            <input name="_method" type="hidden" value="PUT">
            {!! csrf_field() !!}
            <div class="tab-content">

                <div id="id-strip" class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div id="id-strip-ucid" class="col-sm-12 col-md-7">Unique Client ID: <strong>{{ $euci }}</strong></div>
                            <div id="id-strip-review-period" class="col-sm-12 col-md-5">
                                OMB Number: <strong>0906-0033</strong>
                                &nbsp; &nbsp;
                                Expiration Date: <strong>12-31-2020</strong>
                            </div>
                        </div>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane active" id="tab-pane1">
                    @include('includes.s-intro')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane2">
                    @include('includes.s-demographics')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane3">
                    @include('includes.s-access')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane4">
                    @include('includes.s-stigma')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane5">
                    @include('includes.s-medical')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane6">
                    @include('includes.s-trauma')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane7">
                    @include('includes.s-coping')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane8">
                    @include('includes.s-case')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane9">
                    @include('includes.s-substance')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-pane10">
                    @include('includes.s-closing')
                    <nav class="form-nav">
                        <ul class="pager">
                            <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Previous</a></li>
                            <li><input type="submit" class="btn btn-secondary modal-skip" formnovalidate="formnovalidate" name="action" value="Save as Pending"></li>
                            <li class="pull-right"><input type="submit" class="btn btn-primary" name="action" value="Finish and Submit"></li>
                        </ul>
                    </nav>
                </div>

            </div>
        </form>
    </div>

    <div id="modal-survey" class="modal fade" tabindex="-1" role="dialog" data-target="survey">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <p>
                        Click <strong class="text-primary">OK</strong> to finalize the form
                        or <strong class="text-danger">Cancel</strong> to edit.
                        You will not be able to change this information after clicking <strong class="text-primary">OK</strong>.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary modal-ok">OK</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
@endsection

@section('footer')
    <div class="container-fluid">
        <div class="well well-sm">Public Burden Statement: An agency may not conduct or sponsor, and a person is not required to respond to, a collection of information unless it displays a currently valid OMB control number.  The OMB control number for this project is 0906-0033.  Public reporting burden for this collection of information is estimated to average 30 minutes per interview. Send comments regarding this burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to HRSA Reports Clearance Officer, 5600 Fishers Lane, Room 10-29, Rockville, Maryland, 20857.</div>
    </div>
@endsection

@section('scripts')
    <script>
        jQuery(document).ready(function () {
        	var data = <?php echo json_encode($data); ?>;
	        // populate the form with previous input
	        for (prop in data) {
		        if (data.hasOwnProperty(prop)) {
			        var selector = ':input[name="' + prop + '"], :input[name="' + prop + '[]"]';
			        var tagType = $(selector).attr('type');

			        if (tagType === 'radio' || tagType === 'checkbox') {
				        var responses = Array.isArray(data[prop]) ? data[prop] : [data[prop]];
				        $(selector).filter(function () {
					        return $.inArray(this.value, responses) !== -1;
				        }).prop('checked', true);
			        } else {
				        $(selector).val(data[prop]);
			        }
		        }
	        }

	        // expand sub-sections based on branching logic
	        $('.br:checked, .cbr:checked').trigger('click');
        });
    </script>
@endsection